name: Main

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Lint Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Lint
          token: ${{ secrets.PERSONAL_TOKEN }}
<<<<<<< HEAD
          ref: ${{ github.event.pull_request.head.ref }}
=======
>>>>>>> 6043f02 (chore: move run clause to a separate step)

      - name: Echo stuff
        run: |
          echo "THIS IS MAIN"
          echo $GITHUB_RUN_ID
          echo $GITHUB_SHA
