name: Lint

on:
  workflow_dispatch:

jobs:
  lint:
    name: Check:Lint
    runs-on: ubuntu-latest
    steps:
      - name: Run linter
        run: |
          echo "THIS IS LINTER"
          echo $GITHUB_RUN_ID
          echo ${{ github.event.workflow_run.id }}
          echo $GITHUB_SHA
