name: Main

on:
  push:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Lint Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Lint
          token: ${{ secrets.PERSONAL_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          inputs: '{"pr-number": "${{ github.event.number }}"}'

      - name: Echo stuff
        run: |
          echo "THIS IS MAIN"
          echo $GITHUB_RUN_ID
          echo $GITHUB_SHA
