name: Lint

on:
  workflow_dispatch:

jobs:
  lint:
    name: Check:Lint
    runs-on: ubuntu-latest

    env:
      KUBER: staff-portal-pr-badaboom

    steps:
      - uses: actions/checkout@v1
      # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      - run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}

      - name: Run linter
        run: |
          echo "THIS IS LINTER"
          echo "GITHUB_RUN_ID is $GITHUB_RUN_ID"
          echo "workflow run id is ${{ github.event.workflow_run.id }}"
          echo "gihub sha is $GITHUB_SHA"
          echo "KUBER number is ${{ env.KUBER }}"
          echo "PR number is ${{ env.PR }}"
