name: Lint

on:
  workflow_dispatch:

jobs:
  getprnumber:
    name: Get PR Number
    runs-on: ubuntu-latest
    outputs:
      prNumber: ${{ steps.findPr.outputs.pr }}
    steps:
      - uses: actions/checkout@v1
      # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      - run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}

  lint:
    name: Check:Lint
    needs: [getprnumber]
    runs-on: ubuntu-latest

    env:
      PRN: ${{ needs.getprnumber.outputs.prNumber }}

    steps:
      - name: Run linter
        run: |
          echo "THIS IS LINTER"
          echo "GITHUB_RUN_ID is $GITHUB_RUN_ID"
          echo "workflow run id is ${{ github.event.workflow_run.id }}"
          echo "gihub sha is $GITHUB_SHA"
          echo "PR number is ${{ env.PRN }}"
