name: Lint

on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: "Pull request number to send status check"
        required: false

jobs:
  lint:
    name: Check:Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set status check
        uses: niteoweb/pull_request_status_action@v1.0.0
        with:
          pr_number: ${{ github.event.inputs.pr-number }}
          state: pending
          repository: ${{ github.repository }}
          context: "PR Merge Job / Linter"
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Run linter
        run: |
          echo "THIS IS LINTER"
          echo $GITHUB_RUN_ID
          echo ${{ github.event.workflow_run.id }}
          echo $GITHUB_SHA

      - name: Post link
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = `Your temploy is ready 🎉<br />${{ issue_number }}`
            github.issues.createComment({ 
              issue_number: ${{ github.event.inputs.pr-number }}, 
              owner: context.repo.owner, 
              repo: context.repo.repo, body 
              })

      - name: Set status check
        uses: niteoweb/pull_request_status_action@v1.0.0
        with:
          pr_number: ${{ github.event.inputs.pr-number }}
          state: ${{ job.status }}
          repository: ${{ github.repository }}
          context: "PR Merge Job / Linter"
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
